[package]
name = "server"
version.workspace = true
edition.workspace = true

[dependencies]
axum = "0.7"
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres"] }
tokio = { version = "1.27.0", features = ["full"] }
