[workspace]
# NB: hello and world are intentionally left out cargo will
# promote them to members since they are listed as path deps
members = ["print"]

[workspace.package]
edition = "2021"
version = "0.2.0"
