[package]
name = "app"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
some_dep = { path = "../some_dep" }

[dev-dependencies]
some_dep = { path = "../some_dep", features = ["dev"] }
