[book]
authors = ["Ivan Petkov"]
language = "en"
multilingual = false
src = "."
title = "crane"
description = "A Nix library for building cargo projects."

[build]
create-missing = false

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/ipetkov/crane"
edit-url-template = "https://github.com/ipetkov/crane/edit/master/docs/{path}"
site-url = "https://crane.dev"
cname = "crane.dev"
