[[bin]]
name = "alt"
path = "src/bin/hello.rs"

[[bin]]
name = "bye"

[features]
default = ["some"]
some = []

[package]
build = "cranespecific-dummy.rs"
edition = "2021"
name = "multibin"
version = "0.1.0"
