[package]
name = "client"
version.workspace = true
edition.workspace = true

[dependencies]
gloo = "0.11.0"
shared = { version = "0.1.0", path = "../shared" }
yew = { version = "0.21", features = ["csr"] }
