[package]
name = "bindeps"
version = "0.1.0"
edition = "2021"

[dependencies]
foo = { workspace = true }

[workspace.dependencies]
foo = { path = "./foo", target = "wasm32-unknown-unknown", artifact = ["bin", "cdylib", "staticlib"] }
