[package]
name = "sqlx-example-sqlite-todos"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
futures = "0.3"
sqlx = { version = "0.7.3", features = ["sqlite", "runtime-tokio-native-tls"] }
structopt = "0.3"
tokio = { version = "1.20.0", features = ["rt", "macros"]}
