[package]
name = "server"
version.workspace = true
edition.workspace = true

[dependencies]
axum = "0.7"
shared = { version = "0.1.0", path = "../shared" }
tokio = { version = "1.27.0", features = ["full"] }
tower-http = { version = "0.6", features = ["full"] }
