[package]
name = "alt-registry"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = { version = "*" }
bytes = { version = "*", registry = "sparse-crates" }
epitech_api = { version = "*", registry = "alexandrie" }
