[package]
name = "e2e_tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thirtyfour = "0.31"
tokio = { version = "1.26", features = ["full"] }
anyhow = "1.0"
