[package]
name = "e2e_tests"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thirtyfour = "0.35"
tokio = { version = "1.26", features = ["full"] }
anyhow = "1.0"
