[dependencies]
[dependencies.hello]
path = "../hello"
version = "*"

[dependencies.world]
path = "../world"
version = "*"

[package]
build = "cranespecific-dummy.rs"
name = "print"

[package.edition]
workspace = true

[package.version]
workspace = true
