name: flakehub publish
on:
  workflow_dispatch: # for allowing manual triggers of the workflow
  push:
    tags:
      - "v*.*.*"
jobs:
  publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "DeterminateSystems/nix-installer-action@main"
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          visibility: "public"
