name: Update internal flake dependencies

on:
  workflow_dispatch: # for allowing manual triggers of the workflow
  schedule:
    - cron: '37 16 3,18 * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  update-and-push-deps:
    name: flake update
    runs-on: ubuntu-latest
    environment: flake-update
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: Update flake.lock
      id: flakeupdate
      uses: DeterminateSystems/update-flake-lock@834c491b2ece4de0bbd00d85214bb5e83b4da5c6 # v28
      with:
        token: ${{ secrets.PAT_FLAKE_UPDATE }}
        branch: "automation/flake-update"
        pr-title: "Update internal flake.lock"
        path-to-flake-dir: ./test
        pr-labels: |
          automated
          dependencies
          flake update
    - name: Enable Pull Request Automerge
      run: gh pr merge --squash --delete-branch --auto "${PR_NUMBER}"
      env:
        GH_TOKEN: ${{ secrets.PAT_FLAKE_UPDATE }}
        PR_NUMBER: ${{ steps.flakeupdate.outputs.pull-request-number }}
