name: Update internal flake dependencies

on:
  workflow_dispatch: # for allowing manual triggers of the workflow
  schedule:
    - cron: '37 16 9,24 * *'

permissions:
  contents: read

jobs:
  update-and-push-deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@V27
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v15
      with:
        name: crane
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Update flake.lock
      id: flakeupdate
      uses: DeterminateSystems/update-flake-lock@v21
      with:
        token: ${{ secrets.PAT_FLAKE_UPDATE }}
        branch: "automation/flake-update-internal"
        path-to-flake-dir: ./test
        pr-title: "Update internal flake.lock"
        pr-labels: |
          automated
          dependencies
          flake update
    - name: Enable Pull Request Automerge
      run: gh pr merge --squash --delete-branch --auto ${{ steps.flakeupdate.outputs.pull-request-number }}
      env:
        GH_TOKEN: ${{ secrets.PAT_FLAKE_UPDATE }}

